// Dados do Deal Registration do CHECK POINT — mapeados do portal (Product Interest,
// Distributor, Country, Competitive Replacement, Lead Source). Usados no Passo 2 do RO
// quando o fabricante é "Check Point".

// Países (PT-BR) — lista ampla para o campo "Country".
export const PAISES: string[] = [
  "Afeganistão", "África do Sul", "Albânia", "Alemanha", "Andorra", "Angola", "Antígua e Barbuda",
  "Arábia Saudita", "Argélia", "Argentina", "Armênia", "Austrália", "Áustria", "Azerbaijão",
  "Bahamas", "Bahrein", "Bangladesh", "Barbados", "Bélgica", "Belize", "Benin", "Bielorrússia",
  "Bolívia", "Bósnia e Herzegovina", "Botsuana", "Brasil", "Brunei", "Bulgária", "Burkina Faso",
  "Burundi", "Butão", "Cabo Verde", "Camarões", "Camboja", "Canadá", "Catar", "Cazaquistão",
  "Chade", "Chile", "China", "Chipre", "Cingapura", "Colômbia", "Comores", "Congo (Brazzaville)",
  "Congo (Kinshasa)", "Coreia do Norte", "Coreia do Sul", "Costa do Marfim", "Costa Rica",
  "Croácia", "Cuba", "Dinamarca", "Djibuti", "Dominica", "Egito", "El Salvador",
  "Emirados Árabes Unidos", "Equador", "Eritreia", "Eslováquia", "Eslovênia", "Espanha",
  "Estados Unidos", "Estônia", "Eswatini (Suazilândia)", "Etiópia", "Fiji", "Filipinas",
  "Finlândia", "França", "Gabão", "Gâmbia", "Gana", "Geórgia", "Granada", "Grécia", "Guatemala",
  "Guiana", "Guiné", "Guiné Equatorial", "Guiné-Bissau", "Haiti", "Holanda (Países Baixos)",
  "Honduras", "Hong Kong", "Hungria", "Iêmen", "Ilhas Marshall", "Ilhas Salomão", "Índia",
  "Indonésia", "Irã", "Iraque", "Irlanda", "Islândia", "Israel", "Itália", "Jamaica", "Japão",
  "Jordânia", "Kosovo", "Kuwait", "Laos", "Lesoto", "Letônia", "Líbano", "Libéria", "Líbia",
  "Liechtenstein", "Lituânia", "Luxemburgo", "Macau", "Macedônia do Norte", "Madagascar",
  "Malásia", "Malawi", "Maldivas", "Mali", "Malta", "Marrocos", "Maurício", "Mauritânia",
  "México", "Mianmar (Birmânia)", "Micronésia", "Moçambique", "Moldávia", "Mônaco", "Mongólia",
  "Montenegro", "Namíbia", "Nauru", "Nepal", "Nicarágua", "Níger", "Nigéria", "Noruega",
  "Nova Zelândia", "Omã", "Palau", "Panamá", "Papua-Nova Guiné", "Paquistão", "Paraguai", "Peru",
  "Polônia", "Portugal", "Quênia", "Quirguistão", "Reino Unido", "República Centro-Africana",
  "República Tcheca", "República Dominicana", "Romênia", "Ruanda", "Rússia", "Samoa",
  "San Marino", "Santa Lúcia", "São Cristóvão e Névis", "São Tomé e Príncipe",
  "São Vicente e Granadinas", "Senegal", "Serra Leoa", "Sérvia", "Seychelles", "Síria",
  "Somália", "Sri Lanka", "Sudão", "Sudão do Sul", "Suécia", "Suíça", "Suriname", "Tailândia",
  "Taiwan", "Tajiquistão", "Tanzânia", "Timor-Leste", "Togo", "Tonga", "Trinidad e Tobago",
  "Tunísia", "Turcomenistão", "Turquia", "Tuvalu", "Ucrânia", "Uganda", "Uruguai", "Uzbequistão",
  "Vanuatu", "Vaticano", "Venezuela", "Vietnã", "Zâmbia", "Zimbábue",
];

export const CHECKPOINT_CONTACT_TYPE = ["Sales", "Technical"];

// Distribuidores do Check Point (verbatim do portal — com o código do país).
export const CHECKPOINT_DISTRIBUIDORES: string[] = [
  "Computer C- DATA Ltd. | IL", "VISUAL D.G. LTD | IL", "CMS Compucenter Ltd. | IL",
  "PANERA SECURITY LTD | IL", "Ingram Micro, Inc. | US", "TD SYNNEX Canada ULC | CA",
  "Tech Data Corporation | US", "ProWeb | CL", "Ingram Micro Inc - Consumer | US",
  "Hughes Network Systems, LLC | US", "Buckeye CableSystem | US", "Tech Data Canada Corporation | CA",
  "Intersections | US", "TrialPay, Inc. | US", "TD SYNNEX CALA, Inc. | US", "Redington Gulf Fze | AE",
  "TD SYNNEX Corporation | US", "EC America | US", "Desvio, Inc. | US", "Sycomp - Caribbean | US",
  "Avnet, Inc. | US", "Ingram Micro Canada | CA", "AVT Technology Solutions LLC | US",
  "AWS Public Offers | US", "Arrow Enterprise Computing Sol | US", "D&H Distributing Company | US",
  "WG Services | US", "BlackBerry Limited | CA", "AmiViz DMCC | AE", "Ingram Micro, Inc. - CloudBlue | US",
  "Six Degrees Consulting/CDW | US", "AWS Partner Led Offers | US", "WESTCON SAUDI COMPANY L.L.C | SA",
  "WESTCON MIDDLE EAST FZE | AE", "WESTCON DOHA WLL | QA", "Carahsoft Technology Corp | US",
  "Microsoft Azure Partner Led Of | US", "LicenciasOnLine INC | US", "Oracle Public Offers | US",
  "GCP Partner Led Offers | US", "Oracle Partner Led Offers | US", "D&H Canada ULC | CA",
  "DSOR Ingram | US", "DSOR Westcon | US", "DSOR Carahsoft | US", "DSOR TD SYNNEX | US",
  "Techbridge FZCO | AE", "DSOR Arrow | GB", "D&H Distributing Company (Do n | US",
  "D&H Canada ULC (Do not use) | CA", "Pax8 - USD | US", "Atlantic Data SecurityS | US",
  "Worldpay | US", "Merlin Group | US", "REO Westcon | US", "Westcon European Holding Ltd | FR",
  "Westcon Group Germany GmbH | DE", "TD SYNNEX TS Europe B.V. | BE", "Datalink Business Solutions Lt | HK",
  "Westcon Group Pty Limited | AU", "Westcon Spain | ES", "Arrow ECS Denmark | DK", "Westcon Belux | BE",
  "Arrow ECS UK | GB", "Clico Sp. z.o.o | PL", "SB C&S Corp. | JP", "DNS a.s. | CZ",
  "Arrow ECS Finland | FI", "Arrow ECS Austria | AT", "Westcon Netherlands | NL", "Westcon Portugal | PT",
  "Arrow ECS Germany | DE", "TD SYNNEX Brasil LTDA | BR", "Infonet Bilgi Teknolojileri Ti | TR",
  "Cybertech Projects Ca | VE", "V-Valley Advanced Solutions Po | PT", "ACW Distribution (HK) Limited | HK",
  "Westcon Mexico, S.A. de C.V. | MX", "Westcon UK | GB", "Odyssey Consultants Limited | CY",
  "Westcon South Africa | ZA", "Climb Global Solutions EMEA Ir | IE", "Arrow ECS Sweden | SE",
  "Digital China Technology LTD. | CN", "Neteks Teknoloji Urunleri A.S. | TR", "Arrow ECS Czech Republic | CZ",
  "M-Solutions Technology (Thaila | TH", "Westcon Benelux BV | NL", "Arrow ECS Italy | IT",
  "Tarsus Distribution Pty Limite | ZA", "M.Tech Products P/L | SG", "Misoft JSC | VN", "MAPS | MX",
  "MONT LLC - DO NOT USE | RU", "Esprinet | IT", "Arrow ECS Switzerland | CH",
  "M-Security Technology Sdn Bhd | MY", "MPS Mayorista de Colombia | CO", "Licencias On Line S.A.C. PERU | PE",
  "Licencias Online S.A. ARGENTIN | AR", "Asgent, Inc. | JP", "PT M.TECH PRODUCTS | ID",
  "M.Tech (Shanghai) Co., Ltd. | CN", "BD Enterprise | RU", "Westcon Group (NZ) Limited | NZ",
  "MITSUI KNOWLEDGE INDUSTRY CO., | JP", "M-SECURITY TECH PHILIPPINES IN | PH", "Infinigate Norge AS | NO",
  "Licencias On Line S.A. CHILE | CL", "Netpoleon Solutions Pte Ltd | SG", "Itwayvad Yazilim ve Donanim Da | TR",
  "Hitachi Solutions, Ltd. | JP", "Infinigate Sverige AB | SE", "Netpoleon Philippines Inc. | PH",
  "Texonic Instruments | IN", "TD SYNNEX Colombia Ltda | CO", "Licencias On Line LOLCOM S.A. | EC",
  "M-Security Tech. Indochina Pte | VN", "Adaptive Netpoleon Malaysia SD | MY", "Ingram Micro Magyarorszag Kft | HU",
  "South Asian Technologies (Pvt) | LK", "Metaage Corporation | TW", "DataGroupIT | NG",
  "TD SYNNEX Belgium B.V. | BE", "TD SYNNEX Argentina S.R.L. | AR", "Arrow ECS Spain | ES",
  "Abris Distribution Inc. | UZ", "OCS Distribution | RU", "Westcon Africa (Kenya) Limited | KE",
  "ITWAY HELLAS SINGLE MEMBER SA | GR", "Arrow ECS Netherlands | NL", "Sektor Ltd | NZ",
  "Scansource Brasil Distribuidor | BR", "ASBIS SK spol. s r.o. | SK", "NEXSYS DE COLOMBIA S.A. | CO",
  "SEC DataCom AS | DK", "Arrow ECS SAS | FR", "Licencias on Line SA URUGUAY | UY", "Masotec Ltda. | BO",
  "Westcon Solutions IMH Pte. Lim | TW", "TD SYNNEX Perú S.A.C. | PE", "TD SYNNEX Chile Limitada | CL",
  "Ingram Micro doo Beograd | RS", "PSI Inc. | JP", "Westcon Group Italy | IT",
  "Netpoleon (Thailand) Co., Ltd. | TH", "Westcon Group (Thailand) Co. L | TH", "Ingram Micro Ljubljana, d.o.o | SI",
  "Takarajoho Inc | JP", "AXIZ (PTY) LTD | ZA", "Arrow ECS Belgium | BE", "INFINIGATE France | FR",
  "SEC DataCom AB | SE", "GMI Technology Inc | CN", "IT DISTRIBUTION LLC | UA",
  "LICENCIAS ON LINE S.A.S. COLOM | CO", "iValue Infosolutions Ltd | IN", "Arrow ECS Portugal | PT",
  "LICENCIAS ON LINE MEXICO S.A d | MX", "FOB MUK DISTRIBUTION LLC | MD", "INGRAM MICRO d.o.o. | HR",
  "LOL Bolivia Servicios Informat | BO", "iValue InfoSolutions Ltd (Sing | SG", "TD SYNNEX Ecuador Cia. Ltda. | EC",
  "Licencias online Paraguay S.A | PY", "Westcon Morocco | MA", "V-Valley Advanced Solutions Es | ES",
  "Axoft International LLC | BY", "Infinigate Deutschland GmbH | DE", "Tech Data Advanced Private Lim | IN",
  "Data IT Group | KE", "ALSO Schweiz AG | CH", "ITC GROUP S.R.L. | BO", "Ingram Micro dooel Skopje | MK",
  "Avnet Romania | RO", "ITC S.A. | PY", "Tech Data Australia | AU", "Tech Data (Singapore) Pte. Ltd | SG",
  "Distributor for testing | GB", "Arrow ECS Poland | PL", "Uniforce Technology Corporatio | TW",
  "Savex Technologies Pvt. Ltd. | SG", "Synergy computers and communic | HK", "Savex Technologies Pvt. Ltd. | IN",
  "SEC DATACOM AS | NO", "Velox LLC | RU", "Terra Inc | JP", "INGRAM MICRO DO BRASIL LTDA | BR",
  "T-Gaia Corporation | JP", "Infinigate (Schweiz) AG | CH", "Cloud Distribution For Commmun | SA",
  "TD Synnex Netherlands B.V. | NL", "SecTec, a.s. | SK", "SoftBank Corp. | JP", "Sektor Ltd | NZ ",
  "DICKER DATA LTD | AU", "Fortis Distribution Ltd. | RU", "Samsung SDS | KR", "Arrow ECS Norway | NO",
  "Ingram Micro Distribution S.R. | RO", "Infinigate Österreich GmbH | AT", "Yamaha Corporation | JP",
  "Tech Data Advanced Private Lim | SG", "NSPH LTD | PH", "Licencias Online Panama S.A | PA", "MONT | RU",
  "Arrow ECS (IRL) Limited | IE", "F9 Distribution Oy | FI", "Alternetivo s.r.o. | CZ",
  "PT INDOPOLEON TECHNOLOGY | ID", "Shanghai Shone Technology | CN", "TD SYNNEX Uruguay S.R.L. | UY",
  "Cross Point Solution Co., Ltd. | JP", "Ingram Micro(China) Limited | HK", "Technology Distribution Africa | NG",
  "OU REILEM | UA", "DCC Technologies | ZA", "JLEAD Information Co., Ltd. | TW", "Elcore Distribution AG | CH",
  "ACA PACIFIC TECHNOLOGY (S) PTE | SG", "ALSO Bulgaria EOOD | BG", "Future Tech Development FZC LL | AE",
  "Espoir Digital Systems FZCO | AE", "SIA BERG TECH | LV", "DAIWABO INFORMATION SYSTEM CO, | JP",
  "ITD Distribucija Doo | MK", "Insung Digital | KR", "ITD Prishtine SH.P.K | XK", "ITD SHPK | AL",
  "V-Valley Africa, SARL AU | MA", "AB S.A. | PL", "ACA PACIFIC GROUP CO., LTD. | TH",
  "F9 Distribution Baltic UAB | LT", "INFO QUEST TECHNOLOGIES S.M.S. | GR", "TECH DATA ARGENTINA S.A. | AR",
  "IT DISTRIBUTION LTD | BY", "V-Valley (Italy) | IT", "M SAN Grupa d.o.o. | HR",
  "COMPUTER 2000 Bulgaria Ltd. | BG", "Cyberint | IL", "MARUBENI INFORMATION SYSTEMS | JP",
  "TD SYNNEX Paraguay S.R.L. | PY", "TD SYNNEX Panama, S.A. | PA", "TD SYNNEX Guatemala, S.A. | GT",
  "Infinigate B.V. | NL", "UNENTEL SOLUCOES TECNOLOGICAS | BR", "Pax8 - EUR | DE", "Pax8 - GBP | GB",
  "Eltau Trade LLP | KZ", "Distecna.com S.A | AR", "Infinigate Belgium bv | BE", "REO Arrow | GB",
  "REO Climb | IE", "DSOR Redington | AE", "Megazone Cloud Corporation | KR", "REO Data3 | AU",
  "Westcon Netherlands | NL ", "A direct deal",
];

// Product Interest (multiseleção) — árvore achatada com a categoria no rótulo (› separa níveis).
export const CHECKPOINT_PRODUCT_INTEREST: string[] = [
  // Hybrid Mesh Network Security
  "Hybrid Mesh › Next-Gen Firewalls › Maestro Hyperscale Firewall",
  "Hybrid Mesh › Next-Gen Firewalls › Data Center Firewall",
  "Hybrid Mesh › Next-Gen Firewalls › Branch Firewall",
  "Hybrid Mesh › Next-Gen Firewalls › Ruggedized Firewall",
  "Hybrid Mesh › Next-Gen Firewalls › Spark Firewall (SMB)",
  "Hybrid Mesh › Cloud Network & App Security › Cloud Firewall",
  "Hybrid Mesh › Cloud Network & App Security › DDOS",
  "Hybrid Mesh › Cloud Network & App Security › WAF",
  "Hybrid Mesh › SASE (SSE & SD-WAN) › SASE Internet Access",
  "Hybrid Mesh › SASE (SSE & SD-WAN) › SASE Enterprise Browser",
  "Hybrid Mesh › SASE (SSE & SD-WAN) › SASE Private Access",
  "Hybrid Mesh › SASE (SSE & SD-WAN) › SD-WAN",
  "Hybrid Mesh › SASE (SSE & SD-WAN) › SaaS Security",
  "Hybrid Mesh › Network Security Mgmt › Smart-1 Appliances",
  "Hybrid Mesh › Network Security Mgmt › Smart-1 Cloud",
  "Hybrid Mesh › Network Security Mgmt › Smart-1 Software",
  "Hybrid Mesh › Network Security Mgmt › Other",
  // Workspace Security
  "Workspace › Email Security",
  "Workspace › Endpoint Security",
  "Workspace › Browser Security",
  "Workspace › Mobile Security",
  "Workspace › Consumer",
  "Workspace › XDR",
  "Workspace › Workspace Bundle",
  // Exposure Management
  "Exposure Management › External Risk Management",
  "Exposure Management › Threat Exposure Management",
  "Exposure Management › ThreatCloud API",
  // AI Security
  "AI Security › Workspace AI Security",
  "AI Security › AI Agent Security",
  "AI Security › AI Red Teaming",
  // Security Services
  "Security Services › Managed Security Services",
  "Security Services › Security Consulting",
  "Security Services › MDR",
  "Security Services › Professional Services",
  "Security Services › Penetration Testing",
  "Security Services › Incident Response",
  "Security Services › Flex Credits",
  // Infinity Platform Agreement
  "Infinity Platform Agreement › Total Protection (pre-scoped allowances)",
  "Infinity Platform Agreement › Commitment Agreement",
];

export const CHECKPOINT_CONCORRENTES: string[] = [
  "Cisco", "Fortinet", "Juniper", "Palo Alto", "McAfee", "FireEye", "Other",
];

export const CHECKPOINT_LEAD_SOURCES: string[] = [
  "Co-Op", "MDF", "CPX", "CheckMe", "CheckUp", "DemoPoint", "Infinity Portal", "White Space", "Other",
];
