// Dados do Deal Registration da GIGAMON — mapeados do portal. Listas verbatim (nomes próprios /
// frases do portal). Usados no Passo 2 do RO quando o fabricante é "Gigamon".
//
// Campos comuns do Passo 1 NÃO se repetem: Project Name -> nome_oportunidade, Project Budget Amount ->
// valor_estimado_usd, Project Description -> descricao_proposta, Estimated Close Date -> data_fechamento,
// Company -> empresa, First/Last/Title/Phone/Email -> responsavel_*, City/Country/State/Zip -> endereco_empresa.
//
// "Gigamon Product Family" (select) e "Customer's Current Environment" (multiselect) têm as opções
// abaixo — ambos NÃO obrigatórios.

// Gigamon Competitors — dual-list (multisseleção). Nomes verbatim do portal.
export const GIGAMON_COMPETITORS: string[] = [
  "No Competitors",
  "Gigamon Incumbent",
  "A10 Networks",
  "Apcon",
  "Arista Networks",
  "Array Networks",
  "CGS Tower Networks",
  "Cisco Systems",
  "cPacket Networks",
  "Cubro",
  "Extreme Networks",
  "F5 Networks",
  "Garland Technology",
  "Microtel Innovation",
  "NetScout",
  "Niagara Networks",
  "NoviFlow",
  "Nubeva Technologies",
  "Palo Alto Networks",
  "ProfiTAP",
  "Radware",
  "Broadcom (Symantec)",
  "Not Listed",
];

// Deal Registration Source — origem do registro (seleção única; verbatim).
export const GIGAMON_DEAL_REG_SOURCE: string[] = [
  "Ecosystem vendor referral",
  "Customer Requested Gigamon",
  "Distributor",
  "Gigamon Funded Marketing Campaign",
  "VAR Outreach/Qualification",
];

// Gigamon Product Family — família de produto (seleção única; NÃO obrigatório).
export const GIGAMON_PRODUCT_FAMILY: string[] = [
  "Accessories",
  "Cloud Suite",
  "GigaVUE H Series",
  "GigaVUE-FM",
  "Support and Services",
  "Taps and Aggregators",
];

// Customer's Current Environment — dual-list (multisseleção; NÃO obrigatório). Nomes verbatim do portal.
export const GIGAMON_CURRENT_ENVIRONMENT: string[] = [
  "Amazon Security Lake",
  "AppDynamics",
  "Armis",
  "Cequence",
  "ClarOTY",
  "Cribl",
  "CrowdStrike",
  "Dell Fort Zero",
  "Dynatrace",
  "Elastic",
  "Equinix",
  "ExtraHop",
  "Kentik",
  "LiveAction",
  "LogRhythm",
  "Mandiant",
  "Microsoft Sentinel",
  "Nozomi",
  "Nutanix",
  "Ordr",
  "QRadar",
  "Snowflake",
  "Splunk",
  "Sumo Logic",
  "Trellix",
  "Trend Micro",
  "Vectra",
  "BlueVector",
  "Bro - Zeek",
  "Checkpoint",
  "Corelight",
  "Corvil",
  "Darktrace",
  "DataDog",
  "Datiphy",
  "Empirix",
  "Endace",
  "F5",
  "Fidelis",
  "Firepower",
  "Flowmon",
  "ForeScout",
  "Fortinet",
  "Grafana Labs",
  "Imperva",
  "Infovista",
  "Lastline",
  "McAfee",
  "Netscout",
  "Netwitness",
  "New Relic",
  "NIKSUN",
  "Oracle OCI",
  "Palo Alto Networks",
  "Plixer",
  "Polystar",
  "Rapid7",
  "AppLogic (Sandvine)",
  "Not Disclosed",
  "Security Onion",
  "SolarWinds",
  "Tenable",
  "Viavi",
  "Customer Created Tool",
  "Broadcom",
  "Colasoft",
  "DataBee",
  "Dragos",
  "Gigastor",
  "H5 Audit",
  "Manticore",
  "Maxis",
  "Mobileum",
  "SentinelOne",
  "StellarCyber",
  "Suricata",
  "Google SecOps",
  "Wireshark",
  "Wiz",
  "LUMU",
  "Arctic Wolf",
  "OpenObserve",
  "Zscaler",
];
